package com.jn.business.resume.download;

interface Steps {
	int THERE_IS_NOT_RESTRINCTION_TO_THIS_RECRUITER_TO_VIEW_THIS_RESUME = 200;
	int IS_NOT_THE_OWNER_WHO_IS_DOWNLOADING_THIS_RESUME = 202;
	 int THE_OWNER_IS_WHO_IS_DOWNLOADING_THIS_RESUME = 200;
	 int IT_IS_A_TEXT_MODE_TO_VIEW_THIS_RESUME = 202;
	 int THIS_RESUME_HAS_A_VALID_ALIAS = 200;
	 int IS_A_FREELANCER_RECRUITER = 200;
	 int IS_A_CONSULTING_RECRUITER = 202;
	 int IT_IS_AN_ACTIVE_RESUME = 200;

}
